environment: production
version: "2.1.0"
secret_key: "your-secure-secret-key"

database:
  type: sqlite
  path: "flow_yield_system.db"
  backup_enabled: true
  backup_interval_hours: 6
  retention_days: 90

api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  cors_origins: ["https://yourdomain.com"]
  rate_limit: "100/minute"
  api_key_required: true
  ssl_enabled: false

flow_evm:
  rpc_url: "https://mainnet.evm.nodes.onflow.org"
  chain_id: 747
  gas_price_multiplier: 1.2
  max_gas_price: 50000000000
  confirmation_blocks: 2
  timeout_seconds: 30

risk:
  max_portfolio_risk: 0.25
  var_confidence_level: 0.95
  stress_test_enabled: true
  rebalance_threshold: 0.05
  emergency_stop_loss: 0.20
  max_protocol_allocation: 0.45

ml:
  model_update_frequency: "daily"
  training_data_days: 365
  anomaly_detection_sensitivity: 0.1
  prediction_confidence_threshold: 0.7
  model_validation_enabled: true
  auto_retrain_enabled: true

monitoring:
  health_check_interval: 30
  alert_email_enabled: false
  log_level: "INFO"
  metrics_retention_days: 30